<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="0" ignored="0" total="3" passed="3">
  <reporter-output>
  </reporter-output>
  <suite name="CI tests" duration-ms="1404" started-at="2022-01-05T12:09:26 EST" finished-at="2022-01-05T12:09:28 EST">
    <groups>
    </groups>
    <test name="Greeting DAO Tests" duration-ms="1346" started-at="2022-01-05T12:09:26 EST" finished-at="2022-01-05T12:09:28 EST">
      <class name="com.suminski.tests.dalt.GreetingDAOTests">
        <test-method status="PASS" signature="setup()[pri:0, instance:com.suminski.tests.dalt.GreetingDAOTests@464bee09]" name="setup" is-config="true" duration-ms="607" started-at="2022-01-05T12:09:26 EST" finished-at="2022-01-05T12:09:27 EST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="getNoGreetingMatchingInputFoundMessage()[pri:0, instance:com.suminski.tests.dalt.GreetingDAOTests@464bee09]" name="getNoGreetingMatchingInputFoundMessage" duration-ms="646" started-at="2022-01-05T12:09:27 EST" finished-at="2022-01-05T12:09:28 EST">
          <exception class="dev.suminki.ce.BadConnection">
            <message>
              <![CDATA[There was an error: please try again!]]>
            </message>
            <full-stacktrace>
              <![CDATA[dev.suminki.ce.BadConnection: There was an error: please try again!
at dev.suminki.dal.GreetingDAOImp.getGreeting(GreetingDAOImp.java:29)
at com.suminski.tests.dalt.GreetingDAOTests.getNoGreetingMatchingInputFoundMessage(GreetingDAOTests.java:27)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- dev.suminki.ce.BadConnection -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getNoGreetingMatchingInputFoundMessage -->
        <test-method status="PASS" signature="getRealGreeting()[pri:0, instance:com.suminski.tests.dalt.GreetingDAOTests@464bee09]" name="getRealGreeting" duration-ms="55" started-at="2022-01-05T12:09:28 EST" finished-at="2022-01-05T12:09:28 EST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getRealGreeting -->
      </class> <!-- com.suminski.tests.dalt.GreetingDAOTests -->
    </test> <!-- Greeting DAO Tests -->
    <test name="Greeting Service Tests" duration-ms="44" started-at="2022-01-05T12:09:28 EST" finished-at="2022-01-05T12:09:28 EST">
      <class name="com.suminski.tests.slt.GreetingServiceTests">
        <test-method status="PASS" signature="setup()[pri:0, instance:com.suminski.tests.slt.GreetingServiceTests@4b952a2d]" name="setup" is-config="true" duration-ms="1" started-at="2022-01-05T12:09:28 EST" finished-at="2022-01-05T12:09:28 EST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="getExceptionMessage()[pri:0, instance:com.suminski.tests.slt.GreetingServiceTests@4b952a2d]" name="getExceptionMessage" duration-ms="41" started-at="2022-01-05T12:09:28 EST" finished-at="2022-01-05T12:09:28 EST">
          <exception class="dev.suminki.ce.BadConnection">
            <message>
              <![CDATA[There was an error: please try again!]]>
            </message>
            <full-stacktrace>
              <![CDATA[dev.suminki.ce.BadConnection: There was an error: please try again!
at dev.suminki.sl.GreetingServiceImp.getGreetingService(GreetingServiceImp.java:19)
at com.suminski.tests.slt.GreetingServiceTests.getExceptionMessage(GreetingServiceTests.java:26)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- dev.suminki.ce.BadConnection -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getExceptionMessage -->
      </class> <!-- com.suminski.tests.slt.GreetingServiceTests -->
    </test> <!-- Greeting Service Tests -->
  </suite> <!-- CI tests -->
</testng-results>
